name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]  # Atau cabang yang Anda gunakan

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # Atau versi Node.js yang Anda gunakan

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build-prod

    - name: Deploy
      run: npm run deploy
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BASE_HREF: /angular-boilerplate/
